version: '3'

services:
  app1:
    build: .
    networks:
      - app_network

  app2:
    build: .
    networks:
      - app_network
  app3:
    build: .
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "6080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - app1
      - app2
      - app3

networks:
  app_network:
    driver: bridge